// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftzxizhnwxmiottbkpfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0enhpemhud3htaW90dGJrcGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNTMyNjgsImV4cCI6MjA1NjYyOTI2OH0.6P9Nh8freqzjQPRqBuqs96003Ec4Ty_8KHYIQhw8R7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);